version: '3'

services:
  mariadb:
    container_name: mariadb_app1
    restart: always
    build: ./docker/mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Jakarta"
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5

  django_gunicorn:
    container_name: django_gunicorn_app1
    restart: always
    build: ./docker/django_gunicorn
    volumes:
      - website:/website
      - static:/website/staticfiles
    working_dir: /website
    ports:
      - "8013:8000"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: "service_healthy"

  nginx:
    container_name: nginx_app1
    restart: always
    build: ./docker/nginx
    volumes:
      - static:/static
    ports:
      - "8014:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
  website:
  mariadb: