version: '3'

services:
  django_gunicorn:
    container_name: django_gunicorn_app1
    restart: always
    build: ./docker/django_gunicorn
    volumes:
      - website:/website
      - static:/website/staticfiles
    working_dir: /website
    ports:
      - "8014:8014"
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    container_name: nginx_app1
    restart: always
    build: ./docker/nginx
    volumes:
      - static:/static
    ports:
      - "52.187.66.134:8013:80"
    depends_on:
      - django_gunicorn
  
  mysql:
    container_name: mysql_app1
    restart: always
    build: ./docker/mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Jakarta'

volumes:
  static:
  website:
  mysql: